sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: mayulong622
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tPJ7W9ykuTqhgmJqKGB
    access-key-secret: UMkYbmJvgRexKLzYbeSUmnIKSZMxTb
    bucket-name: haru-1
