sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: mayulong622
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tPJ7W9ykuTqhgmJqKGB
    access-key-secret: UMkYbmJvgRexKLzYbeSUmnIKSZMxTb
    bucket-name: haru-1
  redis:
    host: localhost
    port: 6379
  wechat:
    appid: wxd9a88d50a96cb751
    secret: 940c688adc273eec5c90100edd65b572